# Generated by Django 2.0.6 on 2018-07-09 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(auto_now_add=True)),
                ('cir', models.FileField(upload_to='user_directory_path')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessAccount')),
            ],
        ),
    ]
