# Generated by Django 2.0.6 on 2018-07-09 04:56

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='cir',
            field=models.FileField(upload_to=business.models.user_directory_path),
        ),
    ]
