# Generated by Django 2.0.6 on 2018-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180709_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='month',
            field=models.DateField(),
        ),
    ]
