# Generated by Django 2.0.6 on 2018-07-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20180709_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='month',
            field=models.DateField(verbose_name='month'),
        ),
    ]
