# Generated by Django 2.0.6 on 2018-07-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20180709_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='month',
            field=models.TextField(default='July', editable=False, verbose_name='month'),
        ),
    ]
