# Generated by Django 2.0.6 on 2018-07-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20180709_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='month',
        ),
    ]
