# Generated by Django 2.0.6 on 2018-06-26 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_bank', models.CharField(max_length=20, null=True, verbose_name='Bank Name')),
                ('comp_amount', models.PositiveSmallIntegerField(null=True, verbose_name='Amount (rupees)')),
                ('comp_length', models.PositiveSmallIntegerField(null=True, verbose_name='Length (months)')),
                ('comp_interest', models.PositiveSmallIntegerField(null=True, verbose_name='Ratre of Interest')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bank', models.CharField(max_length=20, null=True, verbose_name='Bank Name')),
                ('current_amount', models.PositiveSmallIntegerField(null=True, verbose_name='Amount (rupees)')),
                ('current_length', models.PositiveSmallIntegerField(null=True, verbose_name='Length (months)')),
                ('current_interest', models.PositiveSmallIntegerField(null=True, verbose_name='Rate of Interest')),
                ('current_duration', models.PositiveSmallIntegerField(null=True, verbose_name='Duration (months)')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('aadhar_number', models.CharField(max_length=12, null=True, unique=True)),
                ('pan_number', models.CharField(max_length=10, null=True, unique=True)),
                ('address', models.TextField(null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('monthly_income', models.PositiveSmallIntegerField(null=True)),
                ('average_monthly_savings', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='currentloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
