# Generated by Django 2.0.6 on 2018-06-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20180628_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedloan',
            name='comp_amount',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Amount (rupees)'),
        ),
        migrations.AlterField(
            model_name='completedloan',
            name='comp_interest',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Rate of Interest'),
        ),
        migrations.AlterField(
            model_name='completedloan',
            name='comp_length',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Length (months)'),
        ),
        migrations.AlterField(
            model_name='currentloan',
            name='current_amount',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Amount (rupees)'),
        ),
        migrations.AlterField(
            model_name='currentloan',
            name='current_duration',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Duration (months)'),
        ),
        migrations.AlterField(
            model_name='currentloan',
            name='current_interest',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Rate of Interest'),
        ),
        migrations.AlterField(
            model_name='currentloan',
            name='current_length',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Length (months)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='average_monthly_savings',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='monthly_income',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
