# Generated by Django 2.0.6 on 2018-06-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20180628_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedloan',
            name='comp_amount',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Amount (rupees)'),
        ),
        migrations.AlterField(
            model_name='completedloan',
            name='comp_bank',
            field=models.CharField(max_length=20, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='completedloan',
            name='comp_interest',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Ratre of Interest'),
        ),
        migrations.AlterField(
            model_name='completedloan',
            name='comp_length',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Length (months)'),
        ),
        migrations.AlterField(
            model_name='currentloan',
            name='current_amount',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Amount (rupees)'),
        ),
        migrations.AlterField(
            model_name='currentloan',
            name='current_bank',
            field=models.CharField(max_length=20, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='currentloan',
            name='current_duration',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Duration (months)'),
        ),
        migrations.AlterField(
            model_name='currentloan',
            name='current_interest',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Rate of Interest'),
        ),
        migrations.AlterField(
            model_name='currentloan',
            name='current_length',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Length (months)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='aadhar_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='average_monthly_savings',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='monthly_income',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='pan_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.PositiveIntegerField(max_length=13, null=True),
        ),
    ]
