# Generated by Django 2.0.6 on 2018-06-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20180628_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='phone',
        ),
    ]
