# Generated by Django 2.0.6 on 2018-06-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_personalinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='phone',
            field=models.BigIntegerField(max_length=13, null=True),
        ),
    ]
