# Generated by Django 2.0.6 on 2018-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_personalinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedloan',
            name='comp_interest',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Rate of Interest'),
        ),
    ]
