# Generated by Django 2.0.6 on 2018-07-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20180628_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
