# Generated by Django 2.0.6 on 2018-07-04 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_auto_20180703_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.PersonalAccount'),
        ),
        migrations.AlterField(
            model_name='currentloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.PersonalAccount'),
        ),
    ]
