# Generated by Django 2.0.6 on 2018-07-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_auto_20180704_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personal.PersonalAccount')),
                ('Currently_Owned_Amount', models.PositiveIntegerField(null=True)),
                ('Previously_Owned_Amount', models.PositiveIntegerField(null=True)),
                ('Total_Number_Of_Overdues_in_Current_Loans', models.PositiveIntegerField(null=True)),
                ('Total_Overdue_Amount_of_Current_Loans', models.PositiveIntegerField(null=True)),
                ('Maximum_Number_of_Days_Amount_is_Overdue_in_Current_Loans', models.PositiveIntegerField(null=True)),
                ('Status', models.CharField(choices=[('P', 'Pending'), ('W', 'Written Off')], max_length=1, null=True)),
                ('Total_Overdue_Amount_of_Completed_Loans', models.PositiveIntegerField(null=True)),
                ('Maximum_Number_of_Days_Amount_is_Overdue_in_Completed_Loans', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
