# Generated by Django 2.0.6 on 2018-07-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_auto_20180712_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duesinfo',
            name='bank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessAccount'),
        ),
    ]
