# Generated by Django 2.0.6 on 2018-07-12 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20180709_1618'),
        ('personal', '0019_auto_20180712_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='duesinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duesinfo',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessAccount'),
        ),
        migrations.AlterUniqueTogether(
            name='duesinfo',
            unique_together={('user', 'bank')},
        ),
    ]
