# Generated by Django 2.0.6 on 2018-07-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0020_auto_20180712_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duesinfo',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessAccount'),
        ),
    ]
