# Generated by Django 2.0.6 on 2018-07-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0021_auto_20180712_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
