# Generated by Django 2.0.6 on 2018-07-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0021_auto_20180712_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personal.PersonalAccount')),
                ('eligibility_score', models.CharField(max_length=3, null=True)),
                ('credit_score', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
