# Generated by Django 2.0.6 on 2018-07-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='eligibility_score',
        ),
    ]
